version: "3.7"

services:
  dvwa_with_modsecurity:
    build:
      context: docker-dvwa-modsecurity
    ports:
      - 80:80
    volumes:
      - ./custom/rules.conf:/etc/modsecurity/custom/rules.conf
      - ./custom/php.ini:/etc/php/7.0/apache2/php.ini